### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [hkawanishi/splurtybyhiromi#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by hkawanishi** [comment]
I added:
<meta name="viewport" content="width=device-width, initial-scale=1.0">
in <head></head> of application.html.erb to fix responsive design of mobile device.  Thanks for the comment.  Let me know if you notice something else.

**Comment by hkawanishi** [comment]
It seemed I failed writing my comment above.  Basically I added a viewport in head.  I guess using 'greater than' and 'less than' sign here would not display well?  Sorry about that.

**Comment by Matt-Lepley** [comment]
The '>' is used for blockquotes in github like this

>  test

you can include code using ` on each side of a line like this

`this is code`

---

Anyways, to the point :)
Thumbs up on adding the code! Now you can close the issue since it has been resolved!
